"""Pydantic schemas for CDS Rules API."""

from datetime import datetime
from typing import Optional, List, Dict, Any
from uuid import UUID
from pydantic import BaseModel, Field


class CDSRuleCondition(BaseModel):
    """Schema for a single rule condition (part of IF clause)."""
    field: str = Field(..., description="Patient data field to check (e.g., 'condition_code', 'hba1c_value')")
    operator: str = Field(..., description="Comparison operator (equals, not_equals, greater_than, less_than, in, contains)")
    value: Any = Field(..., description="Expected value to compare against")


class CDSRuleAction(BaseModel):
    """Schema for a single rule action (part of THEN clause)."""
    type: str = Field(..., description="Action type (alert, recommend_guideline, order_lab, etc.)")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Action-specific parameters")


class CDSRuleBase(BaseModel):
    """Base schema for CDS Rule."""
    rule_name: str = Field(..., max_length=255, description="Unique rule name/identifier")
    description: str = Field(..., description="Human-readable rule description")
    priority: int = Field(0, description="Rule priority (higher = more urgent)")
    conditions: List[Dict[str, Any]] = Field(..., description="IF conditions (list of condition objects)")
    actions: List[Dict[str, Any]] = Field(..., description="THEN actions (list of action objects)")
    active: bool = Field(True, description="Whether rule is currently active")


class CDSRuleCreate(CDSRuleBase):
    """Schema for creating a new CDS Rule."""
    pass


class CDSRuleUpdate(BaseModel):
    """Schema for updating a CDS Rule."""
    rule_name: Optional[str] = Field(None, max_length=255, description="Rule name")
    description: Optional[str] = Field(None, description="Description")
    priority: Optional[int] = Field(None, description="Priority")
    conditions: Optional[List[Dict[str, Any]]] = Field(None, description="Conditions")
    actions: Optional[List[Dict[str, Any]]] = Field(None, description="Actions")
    active: Optional[bool] = Field(None, description="Active status")


class CDSRuleResponse(CDSRuleBase):
    """Schema for CDS Rule response."""
    id: UUID = Field(..., description="Rule ID")
    created_at: datetime = Field(..., description="Date rule was created")
    updated_at: datetime = Field(..., description="Date rule was last updated")

    class Config:
        from_attributes = True


class CDSRuleListResponse(BaseModel):
    """Schema for paginated list of CDS Rules."""
    items: List[CDSRuleResponse] = Field(..., description="List of rules")
    total: int = Field(..., description="Total number of rules")
    page: int = Field(..., description="Current page number")
    page_size: int = Field(..., description="Items per page")
    pages: int = Field(..., description="Total number of pages")


class CDSRuleEvaluationRequest(BaseModel):
    """Schema for evaluating rules against patient data."""
    patient_data: Dict[str, Any] = Field(..., description="Patient data to evaluate rules against")
    rule_ids: Optional[List[UUID]] = Field(None, description="Specific rule IDs to evaluate (if None, evaluate all active rules)")


class CDSRecommendation(BaseModel):
    """Schema for a CDS recommendation generated by a rule."""
    rule_id: UUID = Field(..., description="Rule that generated this recommendation")
    rule_name: str = Field(..., description="Rule name")
    priority: int = Field(..., description="Rule priority")
    actions: List[Dict[str, Any]] = Field(..., description="Actions to take")
    triggered_at: datetime = Field(default_factory=datetime.utcnow, description="When rule was triggered")


class CDSRuleEvaluationResponse(BaseModel):
    """Schema for rule evaluation results."""
    recommendations: List[CDSRecommendation] = Field(..., description="List of triggered recommendations")
    evaluated_rules_count: int = Field(..., description="Number of rules evaluated")
    triggered_rules_count: int = Field(..., description="Number of rules that triggered")
