# Generated by Django 2.2.28 on 2025-11-28
# Clinical letter processing fields for regex extraction and document overlap assignment

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_exportedproject_cdb_search_filter_id_and_more'),
    ]

    operations = [
        # Add regex-extracted fields to Document model
        migrations.AddField(
            model_name='document',
            name='nhs_number',
            field=models.CharField(
                blank=True,
                help_text='NHS Number (10 digits) - extracted via regex',
                max_length=10,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='document',
            name='consultant',
            field=models.CharField(
                blank=True,
                help_text='Consultant/Doctor name - extracted via regex',
                max_length=200,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='document',
            name='specialty',
            field=models.CharField(
                blank=True,
                help_text='Medical specialty/department - extracted via regex',
                max_length=100,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='document',
            name='source_file_type',
            field=models.CharField(
                blank=True,
                help_text='Original file type (csv, xlsx, rtf)',
                max_length=10,
                null=True
            ),
        ),

        # Add overlap configuration fields to ProjectGroup model
        migrations.AddField(
            model_name='projectgroup',
            name='overlap_mode',
            field=models.CharField(
                choices=[
                    ('none', 'No Overlap - Each annotator gets unique documents'),
                    ('full', 'Full Overlap - All annotators annotate all documents'),
                    ('partial', 'Partial Overlap - Specified percentage overlap for validation'),
                ],
                default='full',
                help_text='How documents are distributed among annotators for validation overlap',
                max_length=10
            ),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='overlap_percentage',
            field=models.PositiveSmallIntegerField(
                default=20,
                help_text='Percentage of documents that will be annotated by multiple annotators (for partial mode)'
            ),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='min_annotators_per_doc',
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text='Minimum number of annotators that should annotate overlap documents (for partial mode)'
            ),
        ),
    ]
