# Generated by Django 5.1.13 on 2025-11-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_clinical_letter_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgroup',
            name='min_annotators_per_doc',
            field=models.PositiveSmallIntegerField(default=2, help_text='Minimum number of annotators that should annotate overlap documents (for validation). Only applies to partial overlap mode.'),
        ),
        migrations.AlterField(
            model_name='projectgroup',
            name='overlap_percentage',
            field=models.PositiveSmallIntegerField(default=20, help_text='Percentage of documents that will be annotated by multiple annotators (for partial overlap mode). Range: 0-100. A value of 20 means 20% of documents will be annotated by at least 2 annotators.'),
        ),
    ]
